/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.parking;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
/**
 * ParkingResponse
 */

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-18T02:56:29.710+01:00[Europe/Warsaw]")
public class ParkingResponse {
	@SerializedName("transactionId")
	private Integer transactionId = null;

	@SerializedName("valid")
	private Boolean valid = null;

	public ParkingResponse transactionId(Integer transactionId) {
		this.transactionId = transactionId;
		return this;
	}

	/**
	 * Get transactionId
	 * 
	 * @return transactionId
	 **/
	public Integer getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	public ParkingResponse valid(Boolean valid) {
		this.valid = valid;
		return this;
	}

	/**
	 * Get valid
	 * 
	 * @return valid
	 **/
	public Boolean isValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ParkingResponse parkingResponse = (ParkingResponse) o;
		return Objects.equals(this.transactionId, parkingResponse.transactionId)
				&& Objects.equals(this.valid, parkingResponse.valid);
	}

	@Override
	public int hashCode() {
		return Objects.hash(transactionId, valid);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ParkingResponse {\n");

		sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
		sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
